#!/usr/bin/env python3

from sys import argv

from cuba_weather import weather
from cuba_weather import finder

def main():
    if len(argv) not in [2, 3]:
        print('Se requiere al menos un parámetro!')
        exit(-1)

    location = argv[1]
    response_format = argv[2] if len(argv) == 3 else False

    location = finder.get_location(location)

    print("Solicitando datos de " + location)

    c = weather.RCApiClient(location)
    if location and not response_format:
        print(c.getGeneral())
        print("Temperatura: {temp}°C".format(temp=c.getTemperature()))
        print("Humedad: {hum}%".format(hum=c.getHumidity()))
        print("Presión atmosférica: {hpa} hpa".format(hpa=c.getPressure()))
    elif response_format:
        print(response_format.format(temp=c.getTemperature(), hum=c.getHumidity(), hpa=c.getPressure()))


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(e)